server:
  port: 33561
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:33560/eureka/
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
management:
  endpoints:
    web:
      exposure:
        include: "*"