server:
  port: 20232
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:20230/eureka/
ribbon:
  eureka:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
#debug: true
