server:
  port: 20232
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: order-consumer
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:20230/eureka/
ribbon:
  eureka:
    enabled: true
#feign:
#  hystrix:
#    enabled: true
#debug: true
