server:
  port: 20230
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:20230/eureka/
  server:
    enable-self-preservation: false

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
management:
  endpoints:
    web:
      exposure:
        include: "*"