spring:
  application:
    name: admin-server
server:
  port: 33563
eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://eureka-server:33560/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: logs/out.log  #指向日志文件地址，需与LogBack配置的日志地址一致
logging:
  file: logs/out.log